name: Node.js CI

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Install dependencies in the 'travel_guardian' folder
      - name: Install dependencies
        run: |
          cd travel_guardian
          npm ci
