name: Node.js CI

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the workflow

jobs:
  tests:
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres:15
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: password
    #       POSTGRES_DB: travel_guardian_db
    #     ports:
    #       - 5432:5432

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' 

      # Set DATABASE_URL for Prisma
      - name: Set DATABASE_URL in environment
        run: |
          echo "DATABASE_URL=postgresql://dev:%3EyU2%24Fd%5Exds38xa@tgdb.postgres.database.azure.com:5432/travelguardian?schema=public" >> $GITHUB_ENV

      # Install dependencies in the 'travel_guardian' directory
      - name: Install dependencies
        run: |
          cd travel_guardian
          npm install

      # Run Prisma DB Pull and Generate
      - name: Run Prisma DB Pull and Generate
        run: |
          cd travel_guardian
          npx prisma db pull  
          npx prisma generate

      # Run tests
      - name: Run Tests
        run: |
          cd travel_guardian
          npm run test
